# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane_bundles

# Requires
fastlane_require 'dotenv'



default_platform(:ios)


platform :ios do


  #---------------------------------------
  #---------    Before All   -------------
  #---------------------------------------
  before_all do |lane, options|
    # Load environment variables from .env.secret file
    Dotenv.overload '.env.secret'

  end
  
   #--------------------------------------
  #-------------      SVG    ------------
  #--------------------------------------
  desc "Handle SVG Icons"
  # > bundle exec fastlane generate_svg_icons
  # > bundle exec fastlane generate_svg_icons project_name:"MannaEVCustomer"
  lane :generate_svg_icons do |options|
    svg_generator(project_name: options[:project_name])
  end



end


